### PR TITLE
Add travis config for deploying to PyPI on tags

### PR DESCRIPTION
**Pull request by andhus**

### CODE REVIEW

**Comment by gaby** [comment]
I was thinking of replacing the travis-ci configuration with Github Actions. That way everything is in one place.

**Comment by andhus** [comment]
Sounds good. Just added the `PYPI_API_TOKEN` secret with scope to push to https://pypi.org/project/scantree/, since you're a collaborator can you set up the rest?

**Comment by gaby** [comment]
Sounds good, I can add the rest.

**Comment by andhus** [comment]
~~This must have been accidentally closed!?~~ or no, I see, were planning on moving over to GitHub Actions already by this time :)

**Pull request closed without merging**
